[tool.poetry]
name = "git-stats"
version = "0.1.0"
description = ""
authors = ["Stefan Niederhauser <ghuder5@gmx.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib="3.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
